name: finance_management
description: "A Finance Manager App for offline cash."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  font_awesome_flutter: ^10.7.0
  uuid: ^4.4.0
  intl: ^0.17.0
  fl_chart: ^0.70.2
  lottie: ^1.0.3
  intro_slider: ^3.0.0
  charts_flutter: ^0.12.0
  syncfusion_flutter_charts: ^19.3.59
  path_drawing: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "Images/Logo_2.png"
  min_sdk_android: 21
  remove_alpha_ios: true

flutter:

  uses-material-design: true

  assets:
    - Images/
